sudo: false
language: python

matrix:
  include:
    - env: TOX_ENV=py27-dj13
      python: "2.7"
    - env: TOX_ENV=py27-dj14
      python: "2.7"
    - env: TOX_ENV=py27-dj15
      python: "2.7"
    - env: TOX_ENV=py27-dj16
      python: "2.7"
    - env: TOX_ENV=py27-dj17
      python: "2.7"
    - env: TOX_ENV=py27-dj18
      python: "2.7"
    - env: TOX_ENV=py27-dj19
      python: "2.7"
    - env: TOX_ENV=py27-dj110
      python: "2.7"
    - env: TOX_ENV=py33-dj15
      python: "3.3"
    - env: TOX_ENV=py33-dj16
      python: "3.3"
    - env: TOX_ENV=py33-dj17
      python: "3.3"
    - env: TOX_ENV=py33-dj18
      python: "3.3"
    - env: TOX_ENV=py34-dj15
      python: "3.4"
    - env: TOX_ENV=py34-dj16
      python: "3.4"
    - env: TOX_ENV=py34-dj17
      python: "3.4"
    - env: TOX_ENV=py34-dj18
      python: "3.4"
    - env: TOX_ENV=py34-dj19
      python: "3.4"
    - env: TOX_ENV=py34-dj110
      python: "3.4"
    - env: TOX_ENV=py35-dj18
      python: "3.5"
    - env: TOX_ENV=py35-dj19
      python: "3.5"
    - env: TOX_ENV=py35-dj110
      python: "3.5"
    - env: TOX_ENV=py36-dj110
      python: "3.6"
    - env: TOX_ENV=py36-dj111
      python: "3.6"
    - env: TOX_ENV=py36-dj20
      python: "3.6"
  allow_failures:
    - env: TOX_ENV=py33-dj15
    - env: TOX_ENV=py33-dj16
    - env: TOX_ENV=py33-dj17
    - env: TOX_ENV=py33-dj18

notifications:
  email: false

install:
  - pip install --upgrade pip setuptools tox

cache:
  directories:
    - $HOME/.cache/pip

script:
  - tox -e $TOX_ENV
